### ISSUE TITLE
Need escape value in namespace

### ISSUE THREAD

**Issue by sergiors** [sergiors/sensio-framework-extra-service-provider#7]
When a use something which start \N ou \R, does not work

Ex:

```
test:
  path: /test
  defaults:
    template: "@Sergiors\Note\index.html.twig"

```
